  spring.application.name: masaban-server
  server:
    port: 9001

  # database

  spring:
    config:
      import: file:.env-postgres[.properties]
    datasource:
      url: jdbc:postgresql://localhost:5432/masabandb
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    sql:
      init:
        platform: postgresql
        mode: always
    jpa:
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
